import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import dynamic from './store/dynamic.js'
import cart from './store/cart.js'
import test from './store/test.js'
import '@/assets/style/custom.css'
import '@/assets/style/form.css'
import '@/assets/style/iris-button.css'
import '@/assets/style/styles.css'
import '@/assets/style/styles2.css'
import '@/assets/style/styles3.css'
import '@/assets/style/styles7.css'
import '@/assets/style/chunk.css'
import '@/assets/style/slide.css'
import '@/assets/style/chunk2.css'
import '@/assets/style/chunk3.css'
import '@/assets/style/product.css'
import '@/assets/style/productPage.css'
import '@/assets/style/product2.css'
import '@/assets/style/product3.css'
createApp(App).use(store).use(dynamic).use(cart).use(test).use(router).mount('#app')
